---
resource_types:
- name: epochver
  type: docker-image
  source:
    repository: jcderr/concourse-epochver-resource
    tag: dev
resources:
- name: source
  type: git
  source:
    uri: git@github.com:jcderr/concourse-epochver-resource.git
    branch: initial
    private_key: {{ssh-key}}
- name: version
  type: epochver
  source:
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    bucket: concourse-resource-testing
    key: test/concourse-run-test
- name: docker
  type: docker-image
  source:
    email: {{docker-email}}
    password: {{docker-password}}
    repository: jcderr/concourse-epochver-resource
    username: {{docker-user}}
jobs:
- name: build-container
  plan:
  - get: source
    trigger: true
  - put: docker
    params:
      build: source
      tag: source/ci/dev-tag
- name: test-versioning
  plan:
  - get: docker
    trigger: true
    passed: [build-container]
  - get: version
    params:
      bump:
        build: true
  - put: version
    params:
      file: version/version
